name = "UnsafeAtomics"
uuid = "013be700-e6cd-48c3-b4a1-df204f14c38f"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.2.1"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestFunctionRunner = "792026f5-ac9a-4a19-adcb-47b0ce2deb5d"

[targets]
test = ["Test", "TestFunctionRunner"]
